# wurstmeister
version: '3'
services:
    zookeeper:
        image: strimzi/kafka:latest-kafka-2.6.0
        hostname: zookeeper
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
        - "2181:2181"
        environment:
        - ZOO_MY_ID=1
        - ZOO_PORT=2181
        - ZOO_SERVERS=server.1=zookeeper:2888:3888
        - ALLOW_ANONYMOUS_LOGIN=yes
        - LOG_DIR=/tmp/logs
        volumes:
        - ./data/zookeeper/data:/data
        - ./data/zookeeper/datalog:/datalog
    kafka:
        image: strimzi/kafka:latest-kafka-2.6.0
        hostname: kafka
        command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            LOG_DIR: /tmp/logs
            KAFKA_CREATE_TOPICS: "items:1:2,inventory:1:1:compact"
        volumes:
        - ./data/kafka/data:/var/lib/kafka/data
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/home          
        depends_on:
        - zookeeper
    postgresql:
        image: postgres
        hostname: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: supersecret
    schemaregistry:
        image: confluentinc/cp-schema-registry
        hostname: schemaregistry
        restart: always
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
            SCHEMA_REGISTRY_HOST_NAME: schemaregistry
            SCHEMA_REGISTRY_DEBUG: "true"
        depends_on:
            - zookeeper