#!/bin/bash

if [[ ! -d "data" ]]
then
   mkdir data
   mkdir data/postgres-data
fi
if [[ ! -d "data/postgres-data" ]]
then
   mkdir data/postgres-data
fi

docker-compose -f backbone-compose.yml up 2>&1 1>backend.logs &
