#!/bin/bash
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
if [[ $PWD = */scripts ]]; then
 cd ..
fi

if [[ $# -eq 0 ]];then
  export kcenv="local"
else
  export kcenv=$1
fi
cd ../refarch-kc-ms/fleet-ms/
./scripts/buildDocker.sh

cd ../voyages-ms
./scripts/buildDocker.sh

cd ../../refarch-kc-order-ms/order-command-ms
./scripts/buildDocker.sh

cd ../order-query-ms
./scripts/buildDocker.sh

cd ../../refarch-kc-ui
./scripts/buildDocker.sh
