#!/bin/bash
if [[ $# -eq 0 ]];then
  kcenv="LOCAL"
else
  kcenv=$1
fi
root_folder=$(cd $(dirname $0); cd ..; pwd)


if [[ "$kcenv" == "LOCAL" ]]
then
   echo "---- Build base image for liberty"
   docker build -f ./docker/docker-kc-liberty-local -t ibmcase/kc-base-liberty .
else
   echo "----- Transform pem certificates to java der format"
   openssl x509 -in ./certs/postgresql.pem -inform pem -out ./certs/postgresql.der -outform der
   openssl x509 -in ./certs/es-cert.pem -inform pem -out ./certs/es-cert.der -outform der

   echo "---- Build base image for liberty"
   docker build -f ./docker/docker-kc-liberty -t ibmcase/kc-base-liberty .
   docker tag ibmcase/kc-base-liberty us.icr.io/ibmcaseeda/kc-base-liberty
fi

docker images | grep ibmcase