#!/bin/bash
echo "Deploy helm charts for each project"

if [[ $PWD = */scripts ]]; then
 cd ..
fi

ns="browncompute"
verifyPod(){
  kubectl logs $1 -n $ns
}

echo "###########################"
cd ../refarch-kc-order-ms/order-command-ms/scripts
./deployHelm
cd ../../../refarch-kc

echo "###########################"
cd ../refarch-kc-order-ms/order-query-ms/scripts
./deployHelm
cd ../../../refarch-kc

echo "############################"
cd ../refarch-kc-ms/fleet-ms/scripts
./deployHelm

echo "############################"
cd ../../voyages-ms/scripts/
./deployHelm
cd ../../../refarch-kc/

echo "############################"
cd ../refarch-kc-ui/scripts
./deployHelm
cd ../../refarch-kc/
