#!/bin/bash
echo "Deploy helm charts for each project"

ns="browncompute"
verifyPod(){
  kubectl logs $1 -n $ns
}

echo "############################"

oq=$(helm list | grep kc-orderquery | awk '{print $1}')
if [[ -z "$oq" ]]
then 
  echo "kc-orderquery release not deployed..."
  cd ../../refarch-kc-order-ms/order-query-ms/chart
  helm install orderqueryms/ --name kc-orderquery --namespace browncompute
else 
    echo "kc-orderquery release deployed, here is the pod logs"
fi
podId=$(kubectl get pods -n $ns | grep orderquery | awk '{print $1}')
verifyPod $podId

echo "############################"
oq=$(helm list | grep kc-ordercmd | awk '{print $1}')
if [[ -z "$oq" ]]
then 
  echo "kc-ordercmd release not deployed..."
  cd ../../refarch-kc-order-ms/order-ordercommand-ms/chart
  helm install ordercommandms/ --name kc-ordercmd --namespace browncompute
else 
    echo "kc-ordercmd release deployed, here is the pod logs"
fi
podId=$(kubectl get pods -n $ns | grep ordercommandms | awk '{print $1}')
verifyPod $podId

echo "############################"
oq=$(helm list | grep kc-fleetms | awk '{print $1}')
if [[ -z "$oq" ]]
then 
  echo "kc-fleetms release not deployed..."
  cd ../../refarch-kc-ms/fleet-ms/chart
  helm install fleetms/ --name kc-fleetms --namespace browncompute
else 
    echo "kc-fleetms release deployed, here is the pod logs" 
fi
podId=$(kubectl get pods -n $ns | grep fleetms | awk '{print $1}')
verifyPod $podId