#!/bin/bash
if [[ $PWD != */refarch-kc ]]; then
 echo "Run smoke tests from refarch-kc folder"
 exit 1
fi

echo " ====== Local smoke tests to validate all components"
source ./scripts/setenv.sh LOCAL

smokeTest(){
  echo "#########################"
  echo "Smoke test $1 $PWD
  "
  
  results=$(../$2/scripts/$3 2>&1 | grep $4)
  echo $results
  if [[ -z "$results" ]]
  then
      echo "Test failed or is not perfect for $1"
  else
      echo "Smoke test for $1 works!: $results"
  fi
}

# Verify kafka runs
rep=$(curl http://localhost:9092 2>&1 | grep reply)
if [[ -z "$rep" ]] 
then
  echo "You need to start kafka and zookeeper using the ./scripts/runSolutionLocally script"
  exit 1
fi

# Verify the services run
rep=$(curl http://localhost:3010/ 2>&1| grep app-root)
if [[ -z "$rep" ]] 
then
  echo "The web app for demonstration is not running! Verify with docker ps, and may be run ./scripts/runSolutionLocally script"
  exit 1
fi

# Create an order for GoodManuf
rep=$(curl http://localhost:11080/orders/byManuf/GoodManuf 2>&1 | grep GoodManuf)
current=$(pwd)
if [[ -z "$rep" ]]
then
  echo "Add an order from Good manuf for testing"
  
  cd  ../refarch-kc-order-ms/order-command-ms/scripts/
  ./createOrder.sh
  cd $current
fi

smokeTest fleetms refarch-kc-ms/fleet-ms testGetFleetNames.sh KC-NorthAtlantic
smokeTest voyagesms refarch-kc-ms/voyages-ms testGetVoyages.sh voyageID
smokeTest ordercommandms refarch-kc-order-ms/order-command-ms testGetOrders.sh orderID
smokeTest orderqueryms refarch-kc-order-ms/order-query-ms testGetOrdersGoodManuf.sh orderID
