#!/bin/bash
ecgo " ====== Local smoke test to validate all component"

smokeTest(){
  echo "#########################"
  echo "Smoke test $1"
  
  cd ../../$2
  results=$(./scripts/$3)
  if [[ -z "$results" ]]
  then
      echo "Not good for $1"
  else
      echo "Smoke test for $1 works!: $results"
  fi
}

# Verify kafka runs
rep=$(curl http://localhost:9092 2>&1 | grep reply)
if [[ -z "$rep" ]] 
then
  echo I need to start kafka and zookeeper.
  cd ../docker
  docker-compose -f backbone-compose.yml up &
fi

# Verify the services run


smokeTest fleetms refarch-kc-ms/fleet-ms testGetFleetNames.sh
smokeTest voyagesms refarch-kc-ms/voyages-ms testGetVoyages.sh
smokeTest ordercommandms refarch-kc-order-ms/order-command-ms testGetOrders.sh
smokeTest orderqueryms refarch-kc-order-ms/order-query-ms testGetOrdersGoodManuf.sh
