#!/bin/bash
echo "********************************"
echo "Verify your environment and use docker to create needed images to avoid spoiling your computer"
echo "********************************"

if [[ $PWD = */refarch-kc ]]; then
 cd scripts
fi

echo "Do you have java 1.8?"

jvm=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | grep 1.8)
if [[ $? != 0 ]]
then
  echo "java failed"
else 
    echo $jvm
fi

echo "Do you have maven?"
mvn=$(mvn -version 2>&1 | grep 3.5)
if [[ $? != 0 ]]
then
  echo "mvn failed -> let build a docker java tools image to do not impact your environment"
  docker build -f docker-java-tools -t ibmcase/javatools .
else
  echo $mvn
fi


echo "Do you have node?"
nd=$(node --version | grep 11)
if [[ $? != 0 ]]
then
  echo "node failed -> let build a docker node tools image to do not impact your environment"
  docker build -f docker-node-tools -t ibmcase/nodetools .
else
  echo $nd
fi

echo "Do you have python?"
pv=$(python -V 2>&1 | awk '{ print $2}' | grep "3.")
if [[ $? != 0 || -z $pv ]]
then
  echo "Prefer python 3.0 ... verifying your docker images"
  di=$(docker images 2>&1 | grep "ibmcase/python" )
  if [[ -z $di ]]
  then
    echo "Build a python image"
    docker build -f ../itg-tests/Dockerfile -t ibmcase/python .
  else
    echo good to go
  fi
else
  echo "Good python version $pv"
fi

