#!/bin/bash
root_folder=$(cd $(dirname $0); cd ..; pwd)
. ./script/setenv.sh LOCAL

kafka=$(docker-compose -f ./docker/backbone-compose.yml ps | grep kafka | awk '{ print $1}')
if [[ $? != 0  ]]
then
    docker-compose -f ./docker/backbone-compose.yml up &
fi

solution=$(docker-compose -f ./docker/kc-solution-compose.yml ps | grep kafka | awk '{ print $1}')

docker-compose -f kc-solution-compose.yml up &