#!/bin/bash

if [ $# -eq 2 ]
then
  iksname=$1
  nspace=$2
else
  iksname="fabio-wdc-07"
  nspace="browncompute"
fi
echo "get worker node IP address for $iksname"
ipadd=$(ibmcloud ks workers $iksname | grep kube | awk '{print $2}' | head -n 1)

smokeTest(){
  echo "#########################"
  echo "Smoke test $1"
  port=$(kubectl describe service $1-service -n $nspace |  grep NodePort | grep -v  https | tail -n 1 | awk '{print $3}' | cut -d'/' -f 1 )
  url=$ipadd":"$port
  echo $url
  cd ../../$2
  results=$(./scripts/$3 $url)
  if [[ -z "$results" ]]
  then
      echo "Not good for $1"
  else
      echo "Smoke test for $1 works!: $results"
  fi
}

smokeTest fleetms refarch-kc-ms/fleet-ms testGetFleetNames.sh

smokeTest voyagesms refarch-kc-ms/voyages-ms testGetVoyages.sh
smokeTest ordercommandms refarch-kc-order-ms/order-command-ms testGetOrders.sh
smokeTest orderqueryms refarch-kc-order-ms/order-query-ms testGetOrdersGoodManuf.sh
