#!/bin/bash

if [[ $# -eq 0 ]];then
  kcenv="local"
else
  kcenv=$1
fi

verifyImage() {
    p=$(docker images | egrep -w "seconds|minutes" | grep $1)
    echo $p
    if [[ -z "$p" ]]
    then
        echo "bad build for $1"
    else
        echo "$1 looks good"
    fi
}

verifyImage kcontainer-voyages-ms
verifyImage kcontainer-fleet-ms
verifyImage kcontainer-ui
verifyImage kcontainer-order-command-ms
verifyImage kcontainer-order-query-ms
verifyImage kcontainer-spring-container-ms
